import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { CalcResult } from "./finance";
import { formatMoney, formatPct, type CurrencyCode } from "./currency";

export async function buildReportPdf(args: {
  title: string;
  calculator: "FD" | "TD" | "SD";
  currency: CurrencyCode;
  inputs: Array<[string, string]>;
  result: CalcResult;
  comparisonRows?: Array<[string, string, string, string]>;
  chartPng?: string;
  siteName?: string;
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 40;

  // Header band
  doc.setFillColor(11, 31, 58);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(args.siteName ?? "Deposit Calculator", 40, 32);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Calculate. Compare. Grow.", 40, 52);
  doc.setFontSize(9);
  const dt = new Date().toLocaleString();
  doc.text(dt, W - 40, 32, { align: "right" });
  doc.text(`${args.calculator} report`, W - 40, 52, { align: "right" });
  y = 100;

  doc.setTextColor(20, 20, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(args.title, 40, y);
  y += 18;

  // Inputs table
  autoTable(doc, {
    startY: y,
    head: [["Deposit details", "Value"]],
    body: args.inputs,
    theme: "grid",
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 10, cellPadding: 6 },
    margin: { left: 40, right: 40 },
  });
  // @ts-expect-error jspdf-autotable adds lastAutoTable
  y = doc.lastAutoTable.finalY + 16;

  // Results summary
  const r = args.result;
  autoTable(doc, {
    startY: y,
    head: [["Result", "Value"]],
    body: [
      ["Principal", formatMoney(r.principal, args.currency)],
      ["Interest earned", formatMoney(r.interest, args.currency)],
      ["Total profit", formatMoney(r.totalProfit, args.currency)],
      ["Final maturity value", formatMoney(r.finalValue, args.currency)],
      ["Monthly earnings", formatMoney(r.monthlyEarnings, args.currency)],
      ["Annual earnings", formatMoney(r.annualEarnings, args.currency)],
      ["Growth %", formatPct(r.growthPct, 2)],
      ["Effective annual yield", formatPct(r.effectiveYieldPct, 2)],
    ],
    theme: "striped",
    headStyles: { fillColor: [16, 185, 129] },
    styles: { fontSize: 10, cellPadding: 6 },
    margin: { left: 40, right: 40 },
  });
  // @ts-expect-error
  y = doc.lastAutoTable.finalY + 16;

  // Comparison table
  if (args.comparisonRows && args.comparisonRows.length) {
    autoTable(doc, {
      startY: y,
      head: [["Rate", "Interest", "Final value", "Difference"]],
      body: args.comparisonRows,
      theme: "grid",
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 10, cellPadding: 6 },
      margin: { left: 40, right: 40 },
    });
    // @ts-expect-error
    y = doc.lastAutoTable.finalY + 16;
  }

  if (args.chartPng) {
    if (y > 600) {
      doc.addPage();
      y = 40;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Growth chart", 40, y);
    y += 8;
    try {
      doc.addImage(args.chartPng, "PNG", 40, y, W - 80, 200);
      y += 210;
    } catch {
      /* ignore image errors */
    }
  }

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 130);
  doc.text(
    "Generated by Deposit Calculator. Figures are estimates based on the inputs you provided.",
    40,
    doc.internal.pageSize.getHeight() - 24,
  );

  const filename = `deposit-${args.calculator.toLowerCase()}-report-${Date.now()}.pdf`;
  doc.save(filename);
}
